const CHANGE_SELECT_SORT  = 'CHANGE_SELECT_SORT';
const CHANGE_SEARCH_TEXT  = 'CHANGE_SEARCH_TEXT';
const HANDLE_ADD_NEW_TASK = 'HANDLE_ADD_NEW_TASK';
const HANDLE_DELETE_TASK  = 'HANDLE_DELETE_TASK';
const HANDLE_EDIT_TASK    = 'HANDLE_EDIT_TASK';

export {
  CHANGE_SELECT_SORT,
  CHANGE_SEARCH_TEXT,
  HANDLE_ADD_NEW_TASK,
  HANDLE_DELETE_TASK,
  HANDLE_EDIT_TASK,
}